export const formDefaultVals = {
  name: "",
  lastName: "",
  email: "",
  contactNumber: { countryCode: "PH", number: "" },
  position: "",
  serviceDescription: "",
  facebookUrl: "",
  instagramUrl: "",
  linkedinUrl: "",
  skypeInviteUrl: "",
  twitterUrl: "",
  websiteUrl: "",
  whatsappNumber: { countryCode: "PH", number: "" },
  youtubeUrl: "",
};
